
import './Exhibition.css'

import Gallery from '../../Components/Gallery/Gallery'


import img1 from '../../assets/reusedimages/exhibitionbigimage.svg'
import ReadMore from '../../UseStates/ReadMore'
const Exhibition = () => {
  return (
    <div className='Exhibitioncontainer'>

<div className='exhibitionimagecontainer'>
    <img src={img1} alt="" />
</div>
        <div className='text'>
          <ReadMore 
            content='  
            The Manufacturers Association of Nigeria is pleased to inform you that its 51st Annual General Meeting will hold from Tuesday 17th – Thursday, October 2023 at Lagos Oriental Hotel, Lekki-Epe Expressway, Victoria Island, Lagos State. The annual Made-in-Nigeria Expo tagged MANEXPO 2023 will be featuring once again!
    
            This MANEXPO 2023 is specifically targeted to enhancing our member’s visibility in the emerging African Continental Free Trade Area Agreement (AFCFTA) and its 1.4 billion people market. The Association is desirous of showcasing the strength of the Nigerian Manufacturing Sector to both the Nigerian and African that will be attending this landmark and business-focused exhibition.
            
            We have initiated platforms during and after the event for Business-to-Business (B2B) engagements which shall provide channels for improved business initiation and market access. <br/><br/>
            
            
            The event will showcase an array of Made-in-Nigeria products cutting across our 10 sectors and involving Multinationals, Large Corporations, Medium and Small-Scale manufacturing industries of the Association.
            
            We shall be having an interactive forum with relevant stakeholders from Government Ministries, Departments, and Agencies during the event. Thereafter a tour of the exhibition ground will be undertaken to visit and interactions with members with a view to facilitating general product awareness and government patronage.
            
            In view of the eminent attendance and the publicity that will be generated by this EXPO, it is important for your organization to leverage on the platform to exhibit your products. To this end, we invite you to take part by completing the attached Exhibition Form.
            
            Please on completion of the form, kindly make payment into MAN Access Bank Plc Account: 0034929714 Sort Code: 004152273 or Zenith Bank Plc Account: 1013038082 Sort Code: 057150521. Please forward evidence of payment to the Assistant Director, Membership Services Division or e-mail: joseph.emoleke@manufacturersnigeria.org and copy fidelis.aliu@manufacturersnigeria.org on or before September 15th 2023.
            
            Kindly note that reservation of exhibition booth is on first-come, first served basis. The following officers would be glad to discuss your exhibition propositions/bookings with you: Joseph – 08030878784; Adeyemi – 07032717175; Genevieve – 08111961245. We encourage you to take advantage of this very important three-day Made-in-Nigeria Product Exhibition.
            '
          
          
          />


      
          
            

        </div>

<Gallery/>



    </div>
  )
}

export default Exhibition